### ISSUE TITLE
ZoomEye API SDK Demo

### ISSUE THREAD

**Issue by wrestle** [knownsec/ZoomEye-python#2]
希望能整合一下接口规范以及测试代码

不然这个列表几乎是，使用难度太大。

或者官方能够有一个SDK?

**Comment by nixawk** [comment]
Thanks.

**Comment by nixawk** [comment]
@wrestle Please try [ZooEye API SDK- python demo](https://github.com/ZoomEye/SDK/blob/master/zoomeye.py). If you want more details, please read [README](https://github.com/ZoomEye/SDK/blob/master/README.md) doc.
