### ISSUE TITLE
为何search空字符串会导致expires

### ISSUE THREAD

**Issue by Eglusaxie** [knownsec/ZoomEye-python#49]
zoomeye search "" -num 10 -filter "city,device,device=webcam,city=beijing"
the access token expires, please re-run [zoomeye init] command.it is recommended to use API KEY for initialization!

**Comment by Eglusaxie** [comment]
用的apikey进行的init

**Comment by Eglusaxie** [comment]
windows10 python3.9.6

**Comment by wydsxl** [comment]
> zoomeye search "" -num 10 -filter "city,device,device=webcam,city=beijing"
> the access token expires, please re-run [zoomeye init] command.it is recommended to use API KEY for initialization!

我们会尽快处理，感谢你的反馈。
