### ISSUE TITLE
Error when trying to initialize

### ISSUE THREAD

**Issue by ksarieddine** [knownsec/zoomeye-python#77]
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is it a problem with zoomeye API?

**Comment by wh0am1i** [comment]
We are aware of this issue and are in the process of fixing it. Thanks for your feedback.

**Comment by ksarieddine** [comment]
Thank you. Although initialization is successful, whenever I try to search using the python API it asks me to initialize. I believe it is related to this problem.
