### ISSUE TITLE
初始化apikey成功，但是使用search搜索提示token失效

### ISSUE THREAD

**Issue by Vulner-6** [knownsec/zoomeye-python#79]
![image](https://user-images.githubusercontent.com/56946543/186864431-7b70264b-2767-43b7-8c37-72f9343fc283.png)
![image](https://user-images.githubusercontent.com/56946543/186864885-d0bd70b3-b007-4672-8987-e75512a8a861.png)
当我重新刷新apikey之后，重新初始化，依旧无法正常使用该功能。
是贵公司不再对外开放zoomeye的免费查询下载数据的功能了吗？还是说这是一个BUG？
系统：win10   kali  都尝试了
python版本：3.8.5

**Comment by ksarieddine** [comment]
I am facing the same problem!

**Comment by wh0am1i** [comment]
你用的 zoomeye 的版本是多少？

**Comment by wh0am1i** [comment]
> I am facing the same problem!

zoomeye version is?

**Comment by ksarieddine** [comment]
> 

Zoomeye v2.1.1

**Comment by Vulner-6** [comment]
![image](https://user-images.githubusercontent.com/56946543/187115303-17e2ab74-f593-4215-95c5-282ceea26091.png)
zoomeye v2.1.1
默认使用 pip install 按照贵公司的官方文档安装的。

**Comment by Vulner-6** [comment]
非常感谢，升级到 2.1.2 之后，问题已经解决。
